import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'

interface Profile {
  name: string
  username: string
  school: string
  region: string
  gpa?: number
  sat_score?: number
  ielts?: number
  toefl?: number
  github_url?: string
  about_me?: string
}

interface Achievement {
  title: string
  description: string
  type: string
  date: string
  category: string
}

export const generateProfilePDF = (profile: Profile, achievements: Achievement[]) => {
  const doc = new jsPDF()
  
  // Заголовок
  doc.setFontSize(24)
  doc.setFont('helvetica', 'bold')
  doc.text(profile.name, 105, 20, { align: 'center' })
  
  doc.setFontSize(12)
  doc.setFont('helvetica', 'normal')
  doc.text(`@${profile.username}`, 105, 28, { align: 'center' })
  doc.text(`${profile.school} • ${profile.region}`, 105, 35, { align: 'center' })
  
  // Линия
  doc.setLineWidth(0.5)
  doc.line(20, 40, 190, 40)
  
  let yPos = 50
  
  // About Me section
  if (profile.about_me) {
    doc.setFontSize(16)
    doc.setFont('helvetica', 'bold')
    doc.text('About Me', 20, yPos)
    yPos += 8
    
    doc.setFontSize(10)
    doc.setFont('helvetica', 'normal')
    
    // Split text into lines to fit page width
    const aboutLines = doc.splitTextToSize(profile.about_me, 170)
    doc.text(aboutLines, 20, yPos)
    yPos += (aboutLines.length * 5) + 10
  }
  
  // Академические показатели
  if (profile.gpa || profile.sat_score || profile.ielts || profile.toefl) {
    doc.setFontSize(16)
    doc.setFont('helvetica', 'bold')
    doc.text('Academic Metrics', 20, yPos)
    yPos += 10
    
    doc.setFontSize(11)
    doc.setFont('helvetica', 'normal')
    
    if (profile.gpa) {
      doc.text(`GPA: ${profile.gpa.toFixed(2)}`, 20, yPos)
      yPos += 7
    }
    if (profile.sat_score) {
      doc.text(`SAT Score: ${profile.sat_score}`, 20, yPos)
      yPos += 7
    }
    if (profile.ielts) {
      doc.text(`IELTS: ${profile.ielts.toFixed(1)}`, 20, yPos)
      yPos += 7
    }
    if (profile.toefl) {
      doc.text(`TOEFL: ${profile.toefl}`, 20, yPos)
      yPos += 7
    }
    if (profile.github_url) {
      doc.textWithLink('GitHub Profile', 20, yPos, { url: profile.github_url })
      yPos += 7
    }
    
    yPos += 5
  }
  
  // Awards
  const awards = achievements.filter(a => a.category === 'award')
  if (awards.length > 0) {
    doc.setFontSize(16)
    doc.setFont('helvetica', 'bold')
    doc.text('Awards & Honors', 20, yPos)
    yPos += 10
    
    const awardRows = awards.map(a => [
      a.title,
      a.type.replace('_', ' '),
      a.date,
      a.description || ''
    ])
    
    autoTable(doc, {
      startY: yPos,
      head: [['Achievement', 'Type', 'Date', 'Description']],
      body: awardRows,
      theme: 'striped',
      headStyles: { fillColor: [79, 70, 229] },
      margin: { left: 20, right: 20 },
      styles: { fontSize: 9 }
    })
    
    yPos = (doc as any).lastAutoTable.finalY + 10
  }
  
  // Activities
  const activities = achievements.filter(a => a.category === 'activity')
  if (activities.length > 0) {
    // Новая страница если места мало
    if (yPos > 220) {
      doc.addPage()
      yPos = 20
    }
    
    doc.setFontSize(16)
    doc.setFont('helvetica', 'bold')
    doc.text('Activities & Experience', 20, yPos)
    yPos += 10
    
    const activityRows = activities.map(a => [
      a.title,
      a.type.replace('_', ' '),
      a.date,
      a.description || ''
    ])
    
    autoTable(doc, {
      startY: yPos,
      head: [['Activity', 'Type', 'Date', 'Description']],
      body: activityRows,
      theme: 'striped',
      headStyles: { fillColor: [16, 185, 129] },
      margin: { left: 20, right: 20 },
      styles: { fontSize: 9 }
    })
  }
  
  // Футер
  const pageCount = (doc as any).internal.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setFontSize(8)
    doc.setTextColor(150)
    doc.text(
      `Generated by PortfolioPilot • Page ${i} of ${pageCount}`,
      105,
      285,
      { align: 'center' }
    )
  }
  
  // Скачать
  doc.save(`${profile.username}_portfolio.pdf`)
}